In [ ]:
import numpy as np

In [ ]:
a = np.array([0,10,20,30])
a

array([ 0, 10, 20, 30])

In [ ]:
b = np.array([[1],[2],[3],[4]])
b

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
a+b

array([[ 1, 11, 21, 31],
       [ 2, 12, 22, 32],
       [ 3, 13, 23, 33],
       [ 4, 14, 24, 34]])

In [ ]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#splitting

In [5]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [7]:
np.split(x,[2,3])

[array([0, 1]), array([2]), array([3, 4, 5, 6, 7, 8])]

In [8]:
x[0:2]

array([0, 1])

In [9]:
x[2:3]

array([2])

In [10]:
x[3:]

array([3, 4, 5, 6, 7, 8])

In [12]:
a = np.arange(16).reshape(4,4)

In [13]:
np.split(a,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [14]:
np.split(a,4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [15]:
np.hsplit(a,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [16]:
np.vsplit(a,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
#Merging

In [17]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [19]:
np.hstack((a,a,a))

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
#Copies of arrays

In [20]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [21]:
y = x
y

array([1, 2, 3, 4])

In [22]:
x[2] = -75
x

array([  1,   2, -75,   4])

In [23]:
y

array([  1,   2, -75,   4])

In [25]:
#3D arrays

In [26]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])