In [ ]:
!pip install numpy

In [ ]:
arr = [1,2,3,4]
arr_sq = [element**2 for element in arr]
print(arr_sq)

[1, 4, 9, 16]


In [2]:
import numpy as np

In [ ]:
a_np = np.array(arr)
a_np

array([1, 2, 3, 4])

In [ ]:
a_np**2

array([ 1,  4,  9, 16])

In [ ]:
l = range(100000)
len(l)

100000

In [ ]:
%timeit [i**2 for i in l]

31.4 ms ± 405 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
l_np = np.arange(100000)

In [ ]:
len(l_np)

100000

In [ ]:
%timeit l_np**2

81 µs ± 18.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


if you have to perform element wise operation,Numpy Provides
1.Clean Syntax
2.Computation Benfit

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(4,)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(a.ndim,a.shape)

1 (8,)


In [ ]:
a = np.array([1,2,3,4,5,6])
b = len(a)
print(b)

6


In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,5,2)

array([1, 3])

In [ ]:
np.arange(1,5,0.5) #valid for arange not range

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

for generating equally spaced point we use linspace function

In [ ]:
np.linspace(0,100,12) #end point included in the array

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [ ]:
np.array([1,2,3,4,5], dtype = 'float')

array([1., 2., 3., 4., 5.])

Numpy have homogenous characterstics

In [5]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [6]:
arr2 = np.array([1,2,3,4.0])
print(arr2)

[1. 2. 3. 4.]


In [7]:
# Working with 2D arrays

In [8]:
ml = np.array([[1,2,3],[4,5,6]])
ml

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
ml.ndim

2

In [10]:
ml.shape

(2, 3)

In [19]:
a_np = np.array([[2,3,4],[1,2,3]])
a_np

array([[2, 3, 4],
       [1, 2, 3]])

In [20]:
a_np.shape

(2, 3)

In [25]:
a_np.reshape(3,2)

array([[2, 3],
       [4, 1],
       [2, 3]])

In [28]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [31]:
a.T

array([1, 2, 3, 4])

In [34]:
print(a)

<built-in method transpose of numpy.ndarray object at 0x7c1ceb84fab0>


In [35]:
a = np.arange(12).reshape(3,4)

In [36]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [49]:
a = np.arange(1,10).reshape(3,3)
a



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a[[1,1,0],[1,2,0]]

array([5, 6, 1])